# Site Build Settings

# Build settings
markdown: kramdown

# set default markdown engine
highlighter: rouge

# set default permalinks, see https://jekyllrb.com/docs/permalinks/
# the .html suffix is necessary when serving static files
permalink: /:title.html

theme: jekyll-theme-schatten
# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-toc
  - jekyll-archives

# Exclude these files/dirs from processing
exclude: [_site, public, _docker, Gemfile, Gemfile.lock, README.md, LICENSE.md]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           'Fabian Stadler'
description:	       'Software Engineer & Architect'
author:              'Fabian Stadler'
url:                 'https://www.fabianstadler.com'

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
# feed:
#   path: rss-feed.xml

# configuration for jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
    - year
  layouts: 
    category: 'category-archive'
    tag: 'tag-archive'
    year: 'year-archive'
  permalinks:
    category: '/categories/:name/'
    tag: '/tags/:name/'
    year: '/:year/'

# config for toc plugin
toc:
  min_level: 2
  max_level: 5

# Add your Google Analytics ID here
google-ID: ''

# configure your pages for the navbar here
navbar-pages:
- {name: 'Bio',   link: '/p/bio.html'}
- {name: 'Posts', link: '/p/posts.html'}
- {name: 'Archive', link: '/p/archive.html'}
- {name: 'Imprint', link: '/p/imprint.html'}
- {name: 'Privacy Policy', link: '/p/privacy-policy.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', icon-class: 'brands', link: 'https://www.github.com/stfab'}
- {icon: 'linkedin', icon-class: 'brands',  link: 'https://www.linkedin.com/in/fabian-stadler-46777b229/'}
- {icon: 'mastodon', icon-class: 'brands',  link: 'https://mastodon.world/@fabianstadler'}
- {icon: 'envelope', icon-class: 'solid', link: 'mailto:mail@fabianstadler.com'}
- {icon: 'square-rss', icon-class: 'solid', link: '/feed.xml'}

# the copyright year for the footer, comment out to disable
copyright: 2023

# the license for the footer and the link, comment out to disable
license: 'CC BY-SA 4.0 Attribution-ShareAlike 4.0 International.'
license-link: 'https://github.com/stfab/my-website/blob/master/LICENSE'
