version: "1.0"

services:
  jekyll:
    image: jvconseil/jekyll-docker:4.3.2
    volumes:
      - ./../:/srv/jekyll
    ports:
      - 4000:4000
    # update ruby gems
    command: |
      bash -c
      "gem update --system &&
      bundle install &&
      bundle exec jekyll serve --trace --watch --force_polling --host 0.0.0.0"